---
title: "R Notebook"
output: html_notebook
---
```{r}
rm(list = ls())
library(tidyverse)
library(ggplot2)
library(lmtest)
library(Hmisc)
library(MASS)
library(dplyr)
```

```{r}
rm(list = ls())
df = read.table("../data/bumpus.txt", header = TRUE, sep = "\t")
df <- subset(df, select = -c(ID))
summary(df)
df$Survival <- as.integer(df$Survival)
df$Sex <- as.factor(df$Sex)
```

```{r}
summary(df)
head(df)
str(df$Sex)
str(df$Survival)
```

```{r}
table.sex_survival = xtabs(~ df$Sex + df$Survival)
table.sex_survival = as.matrix(table.sex_survival)
summary(table.sex_survival)
```

```{r}
# univariable analysis
log.sex          = glm(Survival ~ Sex , family = binomial(link = logit),data=df)
log.len          = glm(Survival ~ TotalLength , family = binomial(link = logit),data=df)
log.alar         = glm(Survival ~ AlarExtent , family = binomial(link = logit),data=df)
log.weight       = glm(Survival ~ Weight , family = binomial(link = logit),data=df)
log.beak         = glm(Survival ~ BeakHead , family = binomial(link = logit),data=df)
log.humerus      = glm(Survival ~ Humerus , family = binomial(link = logit),data=df)
log.femur        = glm(Survival ~ Femur , family = binomial(link = logit),data=df)
log.tibiotarsus  = glm(Survival ~ Tibiotarsus , family = binomial(link = logit),data=df)
log.skull        = glm(Survival ~ SkullWidth , family = binomial(link = logit),data=df)
log.sternum      = glm(Survival ~ Sternum , family = binomial(link = logit),data=df)

summary(log.sex)
summary(log.len)  
summary(log.alar)
summary(log.weight)
summary(log.beak)
summary(log.humerus)
summary(log.femur)
summary(log.tibiotarsus)
summary(log.skull)
summary(log.sternum)

# Sex         0.3190 0.0786 *
# Len         0.00432 0.00449 **
# Alar        0.441 0.432 
# Weight      0.0133 0.0146 **
# Beak        0.449 0.440
# Humerus     0.0363 0.0344 **
# Femur       0.121 0.116 **
# Tibiotarsus 0.183 0.175 **
# Skull       0.695 0.683
# Sternum     0.121 0.114 **

# len, weight, humerus, femur, tibiotarsus, sternum
```

```{r}
#sex interaction on measurements
log.sex1 = glm(Survival ~ Sex + TotalLength + Sex:TotalLength, family = binomial(link = logit),data=df)
log.sex2 = glm(Survival ~ Sex + AlarExtent + Sex:AlarExtent, family = binomial(link = logit),data=df)
log.sex3 = glm(Survival ~ Sex + Weight + Sex:Weight, family = binomial(link = logit),data=df)
log.sex4 = glm(Survival ~ Sex + BeakHead + Sex:BeakHead, family = binomial(link = logit),data=df)
log.sex5 = glm(Survival ~ Sex + Humerus + Sex:Humerus, family = binomial(link = logit),data=df)
log.sex6 = glm(Survival ~ Sex + Femur + Sex:Femur, family = binomial(link = logit),data=df)
log.sex7 = glm(Survival ~ Sex + Tibiotarsus + Sex:Tibiotarsus, family = binomial(link = logit),data=df)
log.sex8 = glm(Survival ~ Sex + SkullWidth + Sex:SkullWidth, family = binomial(link = logit),data=df)
log.sex9 = glm(Survival ~ Sex + Sternum + Sex:Sternum, family = binomial(link = logit),data=df)

summary(log.sex1)
summary(log.sex2)
summary(log.sex3)
summary(log.sex4)
summary(log.sex5)
summary(log.sex6)
summary(log.sex7)
summary(log.sex8)
summary(log.sex9)

log.femur1 = glm(Survival ~ Femur + Tibiotarsus + Femur:Tibiotarsus, family = binomial(link = logit),data=df)
log.femur2 = glm(Survival ~ Femur + Humerus + Femur:Humerus, family = binomial(link = logit),data=df)
log.humerus1 = glm(Survival ~ Tibiotarsus + Humerus + Tibiotarsus:Humerus, family = binomial(link = logit),data=df)
log.alar1 = glm(Survival ~ AlarExtent + Weight + AlarExtent:Weight, family = binomial(link = logit),data=df)
log.beak1 = glm(Survival ~ BeakHead + SkullWidth + BeakHead:SkullWidth, family = binomial(link = logit),data=df)

summary(log.femur1)
summary(log.femur2)
summary(log.humerus1)
summary(log.alar1)
summary(log.beak1)

#logit(\pi_{i}) = \alpha + \beta_{1}Sex_{i} + \beta_{2}Measurement_{i} + \beta_{3}Sex_{i}*Measurement_{i}

```

```{r}
#find correlated factors
df.cor <- subset(df, select = -c(Survival, Sex))
res <- cor(df.cor)
round(res, 2)

plot(df$AlarExtent, df$TotalLength)
plot(df$Femur, df$Humerus)
plot(df$Femur, df$Tibiotarsus)
plot(df$Humerus, df$Tibiotarsus)

# above r=0.7
## alar-length 0.69, femur-humerus 0.82, femur-tibiotarsus 0.81, humerus-tibiotarsus 0.75
```

```{r}
log.full = glm(Survival ~ . + Sex:TotalLength + Sex:BeakHead + Sex:Humerus + Sex:Sternum + Femur:Humerus + Tibiotarsus:Humerus + AlarExtent:Weight + BeakHead:SkullWidth, family = binomial(link = logit),data=df)
summary(log.full)
```


```{r}
log.step = log.full %>% stepAIC(trace = FALSE)
summary(log.step)

log.step1 = glm(formula = Survival ~ Sex + TotalLength + Weight + Humerus + 
    Sternum + Sex:TotalLength, family = binomial(link = logit), 
    data = df)
summary(log.step1)
```

```{r}
#To assess the statistical significance of each term, we have to ask dropterm() to perform a significance
#test as well. The appropriate test here is a χ
#2
#test (likelihood ratio test):
```